-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-12-10 07:08:34 ICT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE


CREATE TABLE kamar_kost (
    kode_kamar               SMALLINT NOT NULL,
    nama_kamar               VARCHAR(16) NOT NULL,
    fasilitas                VARCHAR(128) NOT NULL,
    harga_sewa               INTEGER NOT NULL,
    rumah_kost_id_rumah_kost SMALLINT NOT NULL,
    penyewa_id_penyewa       SMALLINT
);

ALTER TABLE kamar_kost ADD CONSTRAINT kamar_kost_pk PRIMARY KEY ( kode_kamar );

CREATE TABLE pemasukan (
    id_pemasukan             SERIAL NOT NULL,
    tanggal                  DATE NOT NULL,
    nominal                  INTEGER NOT NULL,
    keterangan               TEXT NOT NULL,
    rumah_kost_id_rumah_kost SMALLINT NOT NULL
);

ALTER TABLE pemasukan ADD CONSTRAINT pemasukan_pk PRIMARY KEY ( id_pemasukan );

CREATE TABLE pemilik_kost (
    id_pemilik_kost                SERIAL NOT NULL,
	nik                            CHAR(16) UNIQUE NOT NULL,
	username                       VARCHAR(16) UNIQUE NOT NULL,
	password                       VARCHAR(12) NOT NULL,
    nama_lengkap                   VARCHAR(32) NOT NULL,
    nama_jalan                     VARCHAR(32) NOT NULL,
    nomor_hp                       CHAR(12) UNIQUE NOT NULL,
    jenis_kelamin 					VARCHAR(16) NOT NULL,
    kota                   			VARCHAR(16) NOT NULL
);

ALTER TABLE pemilik_kost ADD CONSTRAINT pemilik_kost_pk PRIMARY KEY ( id_pemilik_kost );

CREATE TABLE pengeluaran (
    id_pengeluaran           SERIAL NOT NULL,
    tanggal                  DATE NOT NULL,
    nominal                  INTEGER NOT NULL,
    keterangan               TEXT NOT NULL,
    rumah_kost_id_rumah_kost SMALLINT NOT NULL
);

ALTER TABLE pengeluaran ADD CONSTRAINT pengeluaran_pk PRIMARY KEY ( id_pengeluaran );

CREATE TABLE penyewa (
    id_penyewa                     SERIAL NOT NULL,
	nik                            CHAR(16) UNIQUE NOT NULL,
	username                       VARCHAR(16) UNIQUE NOT NULL,
	password                       VARCHAR(12) NOT NULL,
    nama_lengkap                   VARCHAR(32) NOT NULL,
    nama_jalan                     VARCHAR(32) NOT NULL,
    nomor_hp                       CHAR(12) UNIQUE NOT NULL,
    jenis_kelamin 					VARCHAR(16) NOT NULL,
    kota                   			VARCHAR(16) NOT NULL
);

ALTER TABLE penyewa ADD CONSTRAINT penyewa_pk PRIMARY KEY ( id_penyewa );

ALTER TABLE penyewa ADD CONSTRAINT penyewa_nik_un UNIQUE ( nik );

CREATE TABLE rumah_kost (
    id_rumah_kost                SERIAL NOT NULL,
    nama_rumah_kost              VARCHAR(32) NOT NULL,
    nama_jalan                   VARCHAR(32) NOT NULL,
    jenis_kost     				VARCHAR(16) NOT NULL,
    kota                   		 VARCHAR(16) NOT NULL,
    pemilik_kost_id_pemilik_kost SMALLINT NOT NULL
);

ALTER TABLE rumah_kost ADD CONSTRAINT rumah_kost_pk PRIMARY KEY ( id_rumah_kost );

ALTER TABLE kamar_kost
    ADD CONSTRAINT kamar_kost_penyewa_fk FOREIGN KEY ( penyewa_id_penyewa )
        REFERENCES penyewa ( id_penyewa );

ALTER TABLE kamar_kost
    ADD CONSTRAINT kamar_kost_rumah_kost_fk FOREIGN KEY ( rumah_kost_id_rumah_kost )
        REFERENCES rumah_kost ( id_rumah_kost );

ALTER TABLE pemasukan
    ADD CONSTRAINT pemasukan_rumah_kost_fk FOREIGN KEY ( rumah_kost_id_rumah_kost )
        REFERENCES rumah_kost ( id_rumah_kost );

ALTER TABLE pengeluaran
    ADD CONSTRAINT pengeluaran_rumah_kost_fk FOREIGN KEY ( rumah_kost_id_rumah_kost )
        REFERENCES rumah_kost ( id_rumah_kost );

ALTER TABLE rumah_kost
    ADD CONSTRAINT rumah_kost_pemilik_kost_fk FOREIGN KEY ( pemilik_kost_id_pemilik_kost )
        REFERENCES pemilik_kost ( id_pemilik_kost );
		

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
